---
  - name: Download ovftool binaries
    unarchive: src={{ovftool_download_url}} remote_src=True dest={{ tmp_dir }}
  
  - name: Make bundle executable
    file:
      mode: 0755
      path: "{{ tmp_dir }}/{{ file_name }}"


  - name: Install OVFtool
    become: yes
    shell: "{{ tmp_dir }}/{{ file_name }} --eulas-agreed --required --console"
    tags:
      - skip_ansible_lint

  - name: Test that it operates
    command: "ovftool -v"
    changed_when: False